# -*- coding: utf-8 -*-
"""google_trends_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCgJf_CdjZaHSMtJjQ-wfd-CslfjCmGm

# **Google Trends Visualisation**
"""

# =========================================================
# DIGITAL NOSTALGIA TREND ANALYSIS
# Exploring Digital Fatigue and Nostalgic Escapism
# =========================================================

# =========================================================
# IMPORT LIBRARIES
# =========================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# =========================================================
# LOAD DATASET
# =========================================================

df = pd.read_csv("nostalgia.csv")

# Preview dataset columns
print(df.columns)

# =========================================================
# DATA CLEANING
# =========================================================

# Convert Time column into datetime format
df['Time'] = pd.to_datetime(
    df['Time']
)

# =========================================================
# OVERALL GOOGLE TRENDS
# =========================================================

# ---------------------------------------------------------
# PLOT : ALL GOOGLE TRENDS
# ---------------------------------------------------------

plt.figure(figsize=(10,7))

# Plot all trend lines
for column in df.columns[1:]:

    plt.plot(
        df['Time'],
        df[column],
        label=column
    )

# ---------------------------------------------------------
# CULTURAL EVENT MARKERS
# ---------------------------------------------------------

# Pandemic lockdowns
plt.axvline(
    pd.to_datetime('2020-03-01'),
    linestyle='--'
)

plt.text(
    pd.to_datetime('2020-03-01'),
    90,
    'Pandemic',
    rotation=90
)

# TikTok boom
plt.axvline(
    pd.to_datetime('2021-01-01'),
    linestyle='--'
)

plt.text(
    pd.to_datetime('2021-01-01'),
    90,
    'TikTok Boom',
    rotation=90
)

# AI boom
plt.axvline(
    pd.to_datetime('2023-01-01'),
    linestyle='--'
)

plt.text(
    pd.to_datetime('2023-01-01'),
    90,
    'AI Boom',
    rotation=90
)

# ---------------------------------------------------------
# LABELS
# ---------------------------------------------------------

plt.xlabel("Year")

plt.ylabel("Search Interest")

plt.title(
    "Google Trends Over Time"
)

plt.legend()

# SAVE CHART
plt.savefig(
    "google_trends_over_time.png",
    bbox_inches='tight'
)

plt.show()

# =========================================================
# COMPOSITE SCORES
# =========================================================

# DIGITAL FATIGUE SCORE
df['Fatigue'] = df[

    ['Brain rot', 'AI slop', 'Doomscrolling']

].mean(axis=1)

# NOSTALGIA SCORE
df['Nostalgia'] = df[

    ['Film Camera',
     'Vintage',
     'Retro style',
     'Y2K aesthetic',
     '2000s']

].mean(axis=1)

# =========================================================
# DIGITAL FATIGUE VS NOSTALGIA
# =========================================================

# ---------------------------------------------------------
# PLOT : FATIGUE VS NOSTALGIA
# ---------------------------------------------------------

plt.figure(figsize=(7,7))

plt.plot(

    df['Time'],
    df['Fatigue'],

    label='Digital Fatigue'
)

plt.plot(

    df['Time'],
    df['Nostalgia'],

    label='Nostalgia'
)

# ---------------------------------------------------------
# LABELS
# ---------------------------------------------------------

plt.legend()

plt.xlabel("Year")

plt.ylabel("Trend Score")

plt.title(
    "Digital Fatigue vs Nostalgia Trends"
)

# SAVE CHART
plt.savefig(
    "fatigue_vs_nostalgia.png",
    bbox_inches='tight'
)

plt.show()

# =========================================================
# LAG CORRELATION ANALYSIS
# =========================================================

print("\nLag Correlation Results:\n")

lag_results = {}

# Check lag from 0 to 6 months
for lag in range(0, 7):

    shifted_nostalgia = df[
        'Nostalgia'
    ].shift(-lag)

    corr = df[
        'Fatigue'
    ].corr(
        shifted_nostalgia
    )

    lag_results[lag] = corr

    print(
        f"{lag} Month Lag Correlation:",
        round(corr, 3)
    )

# =========================================================
# STRONGEST LAG RELATIONSHIP
# =========================================================

best_lag = max(
    lag_results,
    key=lag_results.get
)

best_corr = lag_results[
    best_lag
]

print("\nStrongest Relationship:")

print(
    f"Nostalgia trends respond strongest "
    f"after {best_lag} month(s)"
)

print(
    f"Correlation = {round(best_corr, 3)}"
)

# ---------------------------------------------------------
# PLOT : LAG CORRELATION
# ---------------------------------------------------------

plt.figure(figsize=(8,5))

plt.plot(

    list(lag_results.keys()),

    list(lag_results.values()),

    marker='o'
)

plt.xlabel("Lag (Months)")

plt.ylabel("Correlation")

plt.title(
    "Lag Correlation Between Digital Fatigue and Nostalgia"
)

plt.grid(True)

# SAVE CHART
plt.savefig(
    "lag_correlation.png",
    bbox_inches='tight'
)

plt.show()

# =========================================================
# INTERPRETATION
# =========================================================

print("\nInterpretation:\n")

if best_corr > 0.5:

    print(
        "A strong positive lag relationship "
        "suggests nostalgia trends may rise "
        "after increases in digital fatigue."
    )

elif best_corr > 0.3:

    print(
        "A moderate positive relationship "
        "suggests possible delayed emotional "
        "responses to online overstimulation."
    )

else:

    print(
        "The lag relationship appears weak, "
        "suggesting limited delayed association."
    )

# =========================================================
# CORRELATION HEATMAP
# =========================================================

# Remove Time column
df_numeric = df.drop(
    columns=['Time']
)

# Calculate correlation matrix
corr = df_numeric.corr()

# ---------------------------------------------------------
# PLOT : HEATMAP
# ---------------------------------------------------------

plt.figure(figsize=(10,8))

sns.heatmap(

    corr,

    annot=True,

    cmap='coolwarm',

    fmt='.2f'
)

plt.title(
    "Correlation Between Nostalgia and Digital Fatigue Trends"
)

# SAVE CHART
plt.savefig(
    "correlation_heatmap.png",
    bbox_inches='tight'
)

plt.show()

# =========================================================
# REGRESSION ANALYSIS
# =========================================================

# ---------------------------------------------------------
# PLOT : DOOMSCROLLING VS VINTAGE
# ---------------------------------------------------------

plt.figure(figsize=(7,7))

sns.regplot(

    x=df['Doomscrolling'],

    y=df['Vintage']
)

plt.title(
    "Relationship Between Doomscrolling and Vintage Trends"
)

# SAVE CHART
plt.savefig(
    "doomscrolling_vs_vintage.png",
    bbox_inches='tight'
)

plt.show()

# =========================================================
# ANALOG VS DIGITAL NOSTALGIA
# =========================================================

# DIGITAL FATIGUE
df['Digital_Fatigue'] = (

    df[['Brain rot',
        'AI slop',
        'Doomscrolling']]

    .mean(axis=1)
)

# ANALOG NOSTALGIA
df['Analog_Nostalgia'] = (

    df[['Film Camera',
        'Vintage',
        'Retro style']]

    .mean(axis=1)
)

# DIGITAL NOSTALGIA
df['Digital_Nostalgia'] = (

    df[['Y2K aesthetic',
        '2000s']]

    .mean(axis=1)
)

# Extract Year
df['Year'] = df[
    'Time'
].dt.year

# Calculate yearly averages
yearly = df.groupby('Year')[

    ['Digital_Fatigue',
     'Analog_Nostalgia',
     'Digital_Nostalgia']

].mean()

# Calculate yearly change
growth = yearly.diff()

# ---------------------------------------------------------
# PLOT : YEARLY CULTURAL TREND CHANGE
# ---------------------------------------------------------

plt.figure(figsize=(14,7))

plt.plot(

    growth.index,

    growth['Digital_Fatigue'],

    label='Digital Fatigue',

    linewidth=3
)

plt.plot(

    growth.index,

    growth['Analog_Nostalgia'],

    label='Analog Nostalgia',

    linewidth=3
)

plt.plot(

    growth.index,

    growth['Digital_Nostalgia'],

    label='Digital Nostalgia',

    linewidth=3
)

# Zero reference line
plt.axhline(0)

# Labels
plt.xlabel("Year")

plt.ylabel(
    "Yearly Change in Search Interest"
)

plt.title(
    "Yearly Change in Cultural Trend Categories"
)

plt.legend()

plt.grid(True)

# SAVE CHART
plt.savefig(
    "yearly_cultural_trend_change.png",
    bbox_inches='tight'
)

plt.show()

# =========================================================
# FASTEST GROWING TERM
# =========================================================

# Remove Time column
trend_data = df.drop(
    columns=['Time']
)

growth = {}

for column in trend_data.columns:

    start_value = trend_data[
        column
    ].iloc[0]

    end_value = trend_data[
        column
    ].iloc[-1]

    total_growth = (
        end_value - start_value
    )

    growth[column] = total_growth

# Find fastest growing term
fastest_term = max(
    growth,
    key=growth.get
)

print("\nFastest Growing Term:\n")

print(fastest_term)

print("\nGrowth Amount:\n")

print(growth[fastest_term])

# =========================================================
# YEARLY GROWTH ANALYSIS
# =========================================================

# Calculate yearly averages
yearly = df.groupby(
    'Year'
).mean(numeric_only=True)

# Calculate yearly change
yearly_change = yearly.diff()

# Average yearly increase
average_growth = yearly_change.mean()

print("\nAverage Yearly Increase:\n")

print(

    average_growth.sort_values(
        ascending=False
    )
)

# =========================================================
# PEAK SEARCH YEARS
# =========================================================

print("\nPeak Search Years:\n")

for column in trend_data.columns:

    peak_index = df[
        column
    ].idxmax()

    peak_year = df.loc[
        peak_index,
        'Time'
    ].year

    peak_value = df[
        column
    ].max()

    print(

        f"{column}: "

        f"{peak_year} "

        f"(Score = {peak_value})"
    )