# -*- coding: utf-8 -*-
"""insta_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sTBXeswW1JiHqCDmxaXGcmdHBFHeiQ6g

# **Instagram Sentiment Analysis**

# sentiment
"""

# =========================================================
# INSTAGRAM ADDICTION SENTIMENT ANALYSIS
# Exploring Digital Fatigue and Online Emotional Responses
# =========================================================

# =========================================================
# IMPORT LIBRARIES
# =========================================================

import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
from sklearn.feature_extraction.text import (
    TfidfVectorizer,
    ENGLISH_STOP_WORDS
)
from wordcloud import WordCloud
import re

# =========================================================
# LOAD DATASET
# =========================================================

_df = pd.read_csv("insta_sentiment_data.csv")

# Preview dataset
print(_df.head())

# =========================================================
# COMBINE TITLE + BODY TEXT
# =========================================================

# Merge title and selftext into one column
_df['text'] = (

    _df['title'].fillna('') + ' ' +

    _df['selftext'].fillna('')
)

# =========================================================
# SENTIMENT DISTRIBUTION
# =========================================================

# Count positive, negative, and neutral posts
sentiment_counts = _df[
    'sentiment_label'
].value_counts()

print("\nSentiment Distribution:\n")

print(sentiment_counts)

# ---------------------------------------------------------
# PIE CHART : SENTIMENT DISTRIBUTION
# ---------------------------------------------------------

plt.figure(figsize=(6,6))

sentiment_counts.plot(
    kind='pie',
    autopct='%1.1f%%'
)

plt.ylabel('')

plt.title(
    'Sentiment Distribution of Instagram Addiction Discussions'
)

# SAVE CHART
plt.savefig(
    "sentiment_distribution.png",
    bbox_inches='tight'
)

plt.show()

# =========================================================
# KEYWORD FREQUENCY ANALYSIS
# =========================================================

# Convert all text into lowercase
text = ' '.join(
    _df['text'].astype(str)
).lower()

# Extract words
words = re.findall(
    r'\b\w+\b',
    text
)

# Count word frequencies
counter = Counter(words)

# ---------------------------------------------------------
# DIGITAL FATIGUE KEYWORDS
# ---------------------------------------------------------

keywords = [

    # addiction-related
    'addiction',
    'dopamine',

    # short-form behavior
    'algorithm',
    'reels',
    'scrolling',

    # mental overload
    'anxiety',

    # attention-span issues
    'attention',
    'distracted',
    'focus',

    # time-wasting behavior
    'wasting',
    'time',

    # short-form content
    'short',
    'content'
]

print("\nKeyword Frequencies:\n")

for word in keywords:

    print(word, ":", counter[word])

# =========================================================
# TF-IDF ANALYSIS
# =========================================================

# Create TF-IDF vectorizer
vectorizer = TfidfVectorizer(
    stop_words='english'
)

# Convert text into TF-IDF matrix
X = vectorizer.fit_transform(
    _df['text'].fillna('')
)

# Get importance scores
scores = zip(

    vectorizer.get_feature_names_out(),

    X.sum(axis=0).tolist()[0]
)

# Sort by importance
sorted_scores = sorted(

    scores,

    key=lambda x: x[1],

    reverse=True
)

print("\nTop TF-IDF Terms:\n")

print(sorted_scores[:20])

# =========================================================
# THEME-BASED ANALYSIS
# =========================================================

themes = {

    # compulsive social media behavior
    'Addiction': [

        'addiction',
        'addicted',
        'dopamine',
        'obsessed',
        'compulsive'
    ],

    # emotional exhaustion
    'Overstimulation': [

        'overwhelmed',
        'overstimulated',
        'stress',
        'burnout',
        'anxiety'
    ],

    # reduced focus and attention span
    'Attention_Problems': [

        'focus',
        'attention',
        'distracted',
        'concentration'
    ],

    # algorithmic short-form content
    'Short_Form_Content': [

        'reels',
        'shorts',
        'scrolling',
        'feed'
    ],

    # desire to disconnect
    'Digital_Detox': [

        'quit',
        'delete',
        'detox',
        'offline',
        'minimalism'
    ]
}

# =========================================================
# COUNT POSTS CONTAINING EACH THEME
# =========================================================

theme_counts = {}

for theme, words in themes.items():

    count = 0

    for text in _df['text'].astype(str).str.lower():

        # Check if any theme-related word exists
        if any(word in text for word in words):

            count += 1

    theme_counts[theme] = count

print("\nTheme Counts:\n")

print(theme_counts)

# ---------------------------------------------------------
# BAR CHART : THEME DISTRIBUTION
# ---------------------------------------------------------

plt.figure(figsize=(8,5))

plt.bar(

    theme_counts.keys(),

    theme_counts.values()
)

plt.title(
    "Themes in Instagram Addiction Discussions"
)

plt.xlabel("Themes")

plt.ylabel("Number of Posts")

plt.xticks(rotation=15)

# SAVE CHART
plt.savefig(
    "theme_distribution.png",
    bbox_inches='tight'
)

plt.show()

# =========================================================
# SENTIMENT BY THEME
# =========================================================

for theme, words in themes.items():

    theme_posts = _df[

        _df['text'].str.lower().apply(

            lambda x: any(

                word in x for word in words
            )
        )
    ]

    sentiment_dist = (

        theme_posts['sentiment_label']

        .value_counts(normalize=True) * 100
    )

    print(f"\n{theme} Sentiment Breakdown:\n")

    print(sentiment_dist.round(2))

# =========================================================
# REMOVE STOPWORDS
# =========================================================

custom_stopwords = {

    'instagram',
    'social',
    'media',
    'people',
    'like',
    'just',
    'really',
    'im',
    'dont',
    'ive'
}

# Combine default + custom stopwords
stop_words = ENGLISH_STOP_WORDS.union(
    custom_stopwords
)

# =========================================================
# TOP WORDS BY SENTIMENT
# =========================================================

for sentiment in _df[
    'sentiment_label'
].unique():

    subset = _df[
        _df['sentiment_label'] == sentiment
    ]

    # Combine text
    text = ' '.join(
        subset['text'].astype(str)
    ).lower()

    # Extract words
    words = re.findall(
        r'\b\w+\b',
        text
    )

    # Remove stopwords and short words
    filtered_words = [

        word for word in words

        if word not in stop_words

        and len(word) > 2
    ]

    # Count frequencies
    counter = Counter(filtered_words)

    print(f"\nTop Words in {sentiment} Posts:\n")

    print(counter.most_common(15))

# =========================================================
# WORD CLOUD
# =========================================================

# Combine all text
all_text = ' '.join(
    _df['text'].astype(str)
).lower()

# Extract words
all_words = re.findall(
    r'\b\w+\b',
    all_text
)

# Remove stopwords
filtered_words = [

    word for word in all_words

    if word not in stop_words

    and len(word) > 2
]

# Join words back together
clean_text = ' '.join(
    filtered_words
)

# Create word cloud
wordcloud = WordCloud(

    width=1200,

    height=600,

    background_color='white'
).generate(clean_text)

# ---------------------------------------------------------
# PLOT : WORD CLOUD
# ---------------------------------------------------------

plt.figure(figsize=(14,7))

plt.imshow(wordcloud)

plt.axis('off')

plt.title(
    "Dominant Terms in Online Discussions"
)

# SAVE CHART
plt.savefig(
    "wordcloud_discussions.png",
    bbox_inches='tight'
)

plt.show()