# -*- coding: utf-8 -*-
"""sales_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PfrEuvWckAitri3fs1NJnjDjZAdx_66L

# instax fuji film sales
"""

# =========================================================
# INSTAX SALES ANALYSIS
# Exploring Analog Photography Consumer Trends
# =========================================================

# =========================================================
# IMPORT LIBRARIES
# =========================================================

import pandas as pd
import matplotlib.pyplot as plt

# =========================================================
# LOAD DATASET
# =========================================================

df = pd.read_csv("instax_sales_transaction_data.csv")

# Preview dataset
print(df.head())

# Display column names
print(df.columns)

# =========================================================
# DATA CLEANING
# =========================================================

# Convert Date column into datetime format
df['Date'] = pd.to_datetime(
    df['Date'],
    format="%d-%m-%Y"
)

# Extract Year from Date
df['Year'] = df['Date'].dt.year

# Remove 2025 because the year is incomplete
df = df[df['Year'] != 2025]

# Create Year-Month column for monthly trend analysis
df['YearMonth'] = df['Date'].dt.to_period('M')

# =========================================================
# MONTHLY SALES TREND
# =========================================================

monthly_qty = df.groupby(
    'YearMonth'
)['Qty'].sum()

print("\nMonthly Quantity Sold:\n")
print(monthly_qty)

# ---------------------------------------------------------
# PLOT : MONTHLY QUANTITY SOLD
# ---------------------------------------------------------

plt.figure(figsize=(12,6))

plt.plot(
    monthly_qty.index.astype(str),
    monthly_qty.values,
    marker='o'
)

plt.title(
    "Monthly Instax Product Sales"
)

plt.xlabel("Month")

plt.ylabel("Total Quantity Sold")

plt.xticks(rotation=45)

plt.grid(True)

# SAVE CHART
plt.savefig(
    "monthly_quantity_sold.png",
    bbox_inches='tight'
)

plt.show()

# =========================================================
# MONTHLY REVENUE TREND
# =========================================================

monthly_revenue = df.groupby(
    'YearMonth'
)['Revenue'].sum()

# ---------------------------------------------------------
# PLOT : MONTHLY REVENUE
# ---------------------------------------------------------

plt.figure(figsize=(12,6))

plt.plot(
    monthly_revenue.index.astype(str),
    monthly_revenue.values,
    marker='o'
)

plt.title(
    "Monthly Revenue Trend"
)

plt.xlabel("Month")

plt.ylabel("Total Revenue")

plt.xticks(rotation=45)

plt.grid(True)

# SAVE CHART
plt.savefig(
    "monthly_revenue_trend.png",
    bbox_inches='tight'
)

plt.show()

# =========================================================
# YEARLY SALES TREND
# =========================================================

yearly_qty = df.groupby(
    'Year'
)['Qty'].sum()

print("\nYearly Quantity Sold:\n")
print(yearly_qty)

# ---------------------------------------------------------
# PLOT : YEARLY SALES TREND
# ---------------------------------------------------------

plt.figure(figsize=(8,5))

plt.plot(
    yearly_qty.index,
    yearly_qty.values,
    marker='o'
)

plt.title(
    "Yearly Quantity Sold"
)

plt.xlabel("Year")

plt.ylabel("Total Quantity Sold")

plt.grid(True)

# SAVE CHART
plt.savefig(
    "yearly_quantity_sold.png",
    bbox_inches='tight'
)

plt.show()

# =========================================================
# CAMERA VS FILM TREND
# =========================================================

category_trend = df.groupby(
    ['YearMonth', 'Category']
)['Qty'].sum().unstack()

print("\nCamera vs Film Trend:\n")
print(category_trend)

# ---------------------------------------------------------
# PLOT : CAMERA VS FILM SALES
# ---------------------------------------------------------

category_trend.plot(
    figsize=(12,6),
    marker='o'
)

plt.title(
    "Camera vs Film Sales Trend"
)

plt.xlabel("Month")

plt.ylabel("Quantity Sold")

plt.xticks(rotation=45)

plt.grid(True)

# SAVE CHART
plt.savefig(
    "camera_vs_film_trend.png",
    bbox_inches='tight'
)

plt.show()

# =========================================================
# TOP SELLING PRODUCTS
# =========================================================

top_products = df.groupby(
    'Product Name'
)['Qty'].sum().sort_values(
    ascending=False
)

print("\nTop Selling Products:\n")
print(top_products.head(10))

# ---------------------------------------------------------
# PLOT : TOP PRODUCTS
# ---------------------------------------------------------

top_products.head(10).plot(
    kind='bar',
    figsize=(10,5)
)

plt.title(
    "Top 10 Selling Products"
)

plt.xlabel("Product")

plt.ylabel("Quantity Sold")

plt.xticks(rotation=45)

# SAVE CHART
plt.savefig(
    "top_selling_products.png",
    bbox_inches='tight'
)

plt.show()

# =========================================================
# SALES CHANNEL ANALYSIS
# =========================================================

channel_sales = df.groupby(
    'Sales Channel'
)['Revenue'].sum().sort_values(
    ascending=False
)

print("\nRevenue by Sales Channel:\n")
print(channel_sales)

# ---------------------------------------------------------
# PLOT : SALES CHANNEL REVENUE
# ---------------------------------------------------------

channel_sales.plot(
    kind='bar',
    figsize=(8,5)
)

plt.title(
    "Revenue by Sales Channel"
)

plt.xlabel("Sales Channel")

plt.ylabel("Revenue")

plt.xticks(rotation=45)

# SAVE CHART
plt.savefig(
    "revenue_by_sales_channel.png",
    bbox_inches='tight'
)

plt.show()

# =========================================================
# FILM VS CAMERA SALES SHARE
# =========================================================

category_sales = df.groupby(
    'Category'
)['Qty'].sum()

# ---------------------------------------------------------
# PIE CHART : CATEGORY SHARE
# ---------------------------------------------------------

plt.figure(figsize=(8,8))

plt.pie(
    category_sales,
    labels=category_sales.index,
    autopct='%1.1f%%'
)

plt.title(
    "Film vs Camera Share of Total Sales"
)

# SAVE CHART
plt.savefig(
    "film_vs_camera_share.png",
    bbox_inches='tight'
)

plt.show()

# =========================================================
# FILM TO CAMERA RATIO
# =========================================================

film_sales = category_sales.get(
    'Film',
    0
)

camera_sales = category_sales.get(
    'Camera',
    0
)

ratio = film_sales / camera_sales

print("\nFilm to Camera Sales Ratio:\n")

print(round(ratio, 2))

# =========================================================
# INTERPRETATION
# =========================================================

if ratio > 1:

    print(
        "\nFilm sales exceed camera sales, "
        "suggesting continued consumer engagement "
        "with analog photography."
    )

else:

    print(
        "\nCamera sales exceed film sales, "
        "suggesting purchases may be more "
        "novelty-driven."
    )